language: node_js
node_js: '10'
script: npm run test && sh build.sh


deploy:
- provider: gcs
  edge: true
  bucket: "$BUCKET_PROD_NAME"
  key_file: "secrets/gcs-prod.json"
  local_dir: dist
  detect_encoding: true
  on:
    branch: master
- provider: gcs
  edge: true
  bucket: "$BUCKET_DEV_NAME"
  key_file: "secrets/gcs-dev.json"
  local_dir: dist
  detect_encoding: true
  on:
    branch: develop

before_deploy:
- openssl aes-256-cbc -K $encrypted_ad9a1014c2de_key -iv $encrypted_ad9a1014c2de_iv
  -in secrets/gcs-dev.json.enc -out secrets/gcs-dev.json -d
- openssl aes-256-cbc -K $encrypted_ad9a1014c2de_key -iv $encrypted_ad9a1014c2de_iv
  -in secrets/gcs-prod.json.enc -out secrets/gcs-prod.json -d
