language: node_js
node_js: '10'
script: npm run test && sh build.sh

before_deploy: firebase use $TRAVIS_BRANCH

deploy:
  - provider: firebase
    edge: true
    on:
      branch: master

  - provider: firebase
    edge: true
    on:
      branch: develop
