language: node_js
node_js: '10'
script: npm run test && sh build.sh


deploy:
- provider: gcs
  edge: true
  bucket: "$BUCKET_PROD_NAME"
  key_file: "gcs-prod.json"
  local_dir: dist
  upload-dir: app
  detect_encoding: true
  on:
    branch: master
- provider: gcs
  edge: true
  bucket: "$BUCKET_DEV_NAME"
  key_file: "gcs-dev.json"
  local_dir: dist
  upload-dir: app
  detect_encoding: true
  on:
    branch: develop

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ad9a1014c2de_key -iv $encrypted_ad9a1014c2de_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
